allOf:
  - $ref: ./EvaluationJobConfigCommon1.yaml
  - type: object
    required:
      - benchmarks
    properties:
      benchmarks:
        type: array
        items:
          $ref: ./EvaluationBenchmarkConfig.yaml
        description: >
          The evaluation benchmarks to run.
      pass_criteria:
        $ref: ./PassCriteriaWithDefault.yaml
        description: >
          The overall pass criteria for the evaluation job.
  - $ref: ./EvaluationJobConfigCommon2.yaml
title: EvaluationJobConfigBenchmarks
